// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class', '.theme-dark'],
  content: ['./index.html', './src/**/*.{ts,tsx,html}'],
  theme: {
    fontFamily: {
      sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif'],
      mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
    },
    extend: {
      colors: {
        // Primary palette (mapped to CSS variables defined in globals.css)
        primary: 'var(--color-primary)',
        'primary-100': 'var(--color-primary-100)',
        'primary-300': 'var(--color-primary-300)',
        'primary-600': 'var(--color-primary-600)',
        'primary-700': 'var(--color-primary-700)',
        'primary-900': 'var(--color-primary-900)',
        // Border hover alias
        'border-hover': 'var(--color-border-hover)',
        base: 'var(--color-bg-base)',
        background: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        elevated: 'var(--color-bg-elevated)',
        panel: 'var(--color-panel)',
        input: 'var(--color-input)',
        code: 'var(--color-code)',
        border: 'var(--color-border)',
        muted: 'var(--color-muted)',
        accent: 'var(--color-accent)',
        'accent-strong': 'var(--color-accent-strong)',
        foreground: 'var(--color-foreground)',
        'muted-foreground': 'var(--color-foreground-muted)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-inverse': 'var(--color-text-inverse)',
        success: 'var(--color-success)',
        'success-600': 'var(--color-success)',
        'success-100': '#d1fae5',
        'success-300': '#6ee7b7',
        'success-900': '#064e3b',
        danger: 'var(--color-danger)',
        'danger-600': 'var(--color-danger)',
        'danger-100': '#fee2e2',
        'danger-300': '#fca5a5',
        'danger-900': '#7f1d1d',
        warning: 'var(--color-warning)',
        'warning-600': 'var(--color-warning)',
        'warning-100': '#fef3c7',
        'warning-300': '#fcd34d',
        'warning-900': '#78350f',
        info: 'var(--color-info)',
      },
      animation: {
        'fadeIn': 'fadeIn 0.5s ease-out',
        'fadeInUp': 'fadeInUp 0.6s ease-out',
        'fadeInDown': 'fadeInDown 0.6s ease-out',
        'slideInRight': 'slideInRight 0.5s ease-out',
        'slideInLeft': 'slideInLeft 0.5s ease-out',
        'scaleIn': 'scaleIn 0.4s ease-out',
        'float': 'float 6s ease-in-out infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'gradient-shift': 'gradient-shift 15s ease infinite',
      },
      keyframes: {
        fadeIn: {
          'from': { opacity: '0' },
          'to': { opacity: '1' },
        },
        fadeInUp: {
          'from': { opacity: '0', transform: 'translateY(20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          'from': { opacity: '0', transform: 'translateY(-20px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          'from': { opacity: '0', transform: 'translateX(-30px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeft: {
          'from': { opacity: '0', transform: 'translateX(30px)' },
          'to': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          'from': { opacity: '0', transform: 'scale(0.9)' },
          'to': { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'gradient-shift': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
      },
      boxShadow: {
        'glow-primary': '0 0 20px rgba(59, 130, 246, 0.3)',
        'glow-success': '0 0 20px rgba(16, 185, 129, 0.3)',
        'glow-danger': '0 0 20px rgba(239, 68, 68, 0.3)',
        'glow-warning': '0 0 20px rgba(245, 158, 11, 0.3)',
      },
    },
  },
  plugins: [],
};

export default config;

