// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
import { ReactNode } from 'react';

export const cn = (...classes: Array<string | undefined | false | null>): string =>
  classes.filter(Boolean).join(' ');

type SectionProps = {
  title: string;
  description?: string;
  action?: ReactNode;
  children: ReactNode;
};

export const Section = ({ title, description, action, children }: SectionProps): JSX.Element => (
  <section className="space-y-3">
    <div className="flex items-center justify-between gap-3">
      <div>
        <h2 className="text-base font-semibold text-foreground">{title}</h2>
        {description && <p className="text-sm text-muted-foreground">{description}</p>}
      </div>
      {action}
    </div>
    {children}
  </section>
);

export default Section;

