import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
// If react-markdown or rehype-highlight are missing, run: pnpm --dir frontend add react-markdown rehype-highlight
import ReactMarkdown from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import { useMemo } from 'react';
const MarkdownRenderer = ({ content, className }) => {
    const memoContent = useMemo(() => content, [content]);
    const components = {
        code({ inline, className: codeClassName, children, ...props }) {
            const language = (codeClassName || '').replace('language-', '');
            if (inline) {
                return (_jsx("code", { className: "rounded bg-muted px-1.5 py-0.5 text-sm", ...props, children: children }));
            }
            const text = String(children).trim();
            return (_jsxs("div", { className: "relative group", children: [_jsx("button", { type: "button", "aria-label": "Copy code", onClick: () => navigator.clipboard.writeText(text), className: "absolute right-2 top-2 rounded border border-border bg-panel px-2 py-1 text-xs text-muted-foreground opacity-0 transition group-hover:opacity-100 focus-visible:opacity-100 focus-visible:ring-2 focus-visible:ring-accent", children: "Copy" }), _jsx("pre", { className: "overflow-auto rounded border border-border bg-code px-3 py-3 text-sm", children: _jsx("code", { className: codeClassName, "data-language": language, ...props, children: children }) })] }));
        },
        h2({ children }) {
            return _jsx("h2", { className: "mt-6 text-lg font-semibold text-foreground first:mt-0", children: children });
        },
        h3({ children }) {
            return _jsx("h3", { className: "mt-4 text-base font-semibold text-foreground", children: children });
        },
        p({ children }) {
            return _jsx("p", { className: "mt-3 text-sm leading-relaxed text-foreground/90", children: children });
        },
        ul({ children }) {
            return _jsx("ul", { className: "mt-3 list-disc space-y-2 pl-5 text-sm text-foreground/90", children: children });
        },
        ol({ children }) {
            return _jsx("ol", { className: "mt-3 list-decimal space-y-2 pl-5 text-sm text-foreground/90", children: children });
        },
        li({ children }) {
            return _jsx("li", { className: "leading-relaxed", children: children });
        },
    };
    return (_jsx("div", { className: className, children: _jsx(ReactMarkdown, { rehypePlugins: [rehypeHighlight], components: components, children: memoContent }) }));
};
export default MarkdownRenderer;
