// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
// If react-markdown or rehype-highlight are missing, run: pnpm --dir frontend add react-markdown rehype-highlight
import ReactMarkdown from 'react-markdown';
import type { Components } from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import { useMemo, type ComponentPropsWithoutRef } from 'react';

type CodeComponentProps = ComponentPropsWithoutRef<'code'> & {
  inline?: boolean;
  node?: unknown;
};

type MarkdownRendererProps = {
  content: string;
  className?: string;
};

const MarkdownRenderer = ({ content, className }: MarkdownRendererProps): JSX.Element => {
  const memoContent = useMemo(() => content, [content]);

  const components: Components = {
    code({ inline, className: codeClassName, children, ...props }: CodeComponentProps) {
      const language = (codeClassName || '').replace('language-', '');
      if (inline) {
        return (
          <code className="rounded bg-muted px-1.5 py-0.5 text-sm" {...props}>
            {children}
          </code>
        );
      }
      const text = String(children).trim();
      return (
        <div className="relative group">
          <button
            type="button"
            aria-label="Copy code"
            onClick={() => navigator.clipboard.writeText(text)}
            className="absolute right-2 top-2 rounded border border-border bg-panel px-2 py-1 text-xs text-muted-foreground opacity-0 transition group-hover:opacity-100 focus-visible:opacity-100 focus-visible:ring-2 focus-visible:ring-accent"
          >
            Copy
          </button>
          <pre className="overflow-auto rounded border border-border bg-code px-3 py-3 text-sm">
            <code className={codeClassName} data-language={language} {...props}>
              {children}
            </code>
          </pre>
        </div>
      );
    },
    h2({ children }) {
      return <h2 className="mt-6 text-lg font-semibold text-foreground first:mt-0">{children}</h2>;
    },
    h3({ children }) {
      return <h3 className="mt-4 text-base font-semibold text-foreground">{children}</h3>;
    },
    p({ children }) {
      return <p className="mt-3 text-sm leading-relaxed text-foreground/90">{children}</p>;
    },
    ul({ children }) {
      return <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-foreground/90">{children}</ul>;
    },
    ol({ children }) {
      return <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-foreground/90">{children}</ol>;
    },
    li({ children }) {
      return <li className="leading-relaxed">{children}</li>;
    },
  };

  return (
    <div className={className}>
      <ReactMarkdown rehypePlugins={[rehypeHighlight]} components={components}>
        {memoContent}
      </ReactMarkdown>
    </div>
  );
};

export default MarkdownRenderer;

