// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
import { PropsWithChildren, ReactNode, useMemo } from 'react';
import { NavLink, useLocation } from 'react-router-dom';
import { useTheme } from './ThemeProvider';
import Button from './ui/Button';

type ShellProps = PropsWithChildren<{ title?: string; actions?: ReactNode }>;

const navItems: Array<{ label: string; to?: string; aria?: string; soon?: boolean }> = [
  { label: 'Jobs', to: '/jobs', aria: 'Go to jobs' },
  { label: 'Workers', to: '/workers', aria: 'Go to workers' },
  { label: 'Settings', soon: true, aria: 'Settings coming soon' },
];

const Shell = ({ children, title, actions }: ShellProps): JSX.Element => {
  const location = useLocation();
  const { theme, toggleTheme } = useTheme();

  const derivedTitle = useMemo(() => {
    if (title) return title;
    if (location.pathname.startsWith('/jobs/') && location.pathname.split('/').length > 2) return 'Job Detail';
    if (location.pathname.startsWith('/workers')) return 'Workers';
    return 'Job Queue';
  }, [location.pathname, title]);

  return (
    <div className="min-h-screen bg-surface text-foreground overflow-x-hidden">
      <div className="flex">
        <aside className="hidden md:flex h-screen w-60 flex-col border-r border-border/50 bg-panel/70 backdrop-blur-xl sticky top-0" role="navigation" aria-label="Primary">
          <div className="relative flex items-center gap-3 px-5 py-5 border-b border-border/50 overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-br from-sky-500/10 via-indigo-500/10 to-purple-500/10" aria-hidden />
            <div className="relative h-10 w-10 rounded-xl bg-gradient-to-br from-sky-400 via-indigo-500 to-purple-600 text-white flex items-center justify-center font-bold text-sm shadow-lg shadow-indigo-500/20">
              DP
            </div>
            <div className="relative font-bold tracking-tight text-lg bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text">DevPilot</div>
          </div>
          <nav className="flex-1 px-3 py-5 space-y-1.5">
            {navItems.map((item) =>
              item.to ? (
                <NavLink
                  key={item.label}
                  to={item.to}
                  aria-label={item.aria}
                  className={({ isActive }) =>
                    `group relative flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium outline-none transition-all duration-200 focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-accent focus-visible:ring-offset-panel ${
                      isActive 
                        ? 'bg-gradient-to-r from-accent/10 to-accent/5 text-accent shadow-sm' 
                        : 'text-muted-foreground hover:bg-gradient-to-r hover:from-muted hover:to-transparent hover:text-foreground hover:scale-[1.02]'
                    }`
                  }
                >
                  {({ isActive }) => (
                    <>
                      {isActive && (
                        <span className="absolute left-0 h-4 w-1 rounded-r bg-accent" aria-hidden />
                      )}
                      <span className={`h-2 w-2 rounded-full transition-all ${isActive ? 'bg-accent shadow-sm shadow-accent' : 'bg-current opacity-50 group-hover:opacity-100'}`} aria-hidden />
                      <span>{item.label}</span>
                    </>
                  )}
                </NavLink>
              ) : (
                <div
                  key={item.label}
                  className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-muted-foreground/50 cursor-not-allowed"
                  aria-label={item.aria}
                >
                  <span className="h-2 w-2 rounded-full bg-border/30" aria-hidden />
                  <span>{item.label}</span>
                  <span className="ml-auto rounded-full bg-muted/50 px-2 py-0.5 text-[10px] uppercase tracking-wide">Soon</span>
                </div>
              ),
            )}
          </nav>
          <div className="border-t border-border/50 bg-gradient-to-b from-transparent to-muted/20 px-4 py-3">
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <div className="h-1.5 w-1.5 rounded-full bg-green-500 animate-pulse" aria-hidden />
              <span>Operational</span>
            </div>
          </div>
        </aside>

        <main className="flex-1 min-w-0">
          <header className="sticky top-0 z-10 border-b border-border/50 bg-panel/80 backdrop-blur-xl supports-[backdrop-filter]:bg-panel/70 shadow-sm">
            <div className="flex items-center gap-4 px-6 py-3.5 w-full">
              <div className="flex-1 min-w-0">
                <p className="text-[10px] uppercase tracking-[0.15em] text-muted-foreground font-medium">DevPilot Phase 3</p>
                <h1 className="text-lg font-bold leading-tight text-foreground truncate">{derivedTitle}</h1>
              </div>
              <div className="hidden sm:flex items-center gap-2 flex-1 max-w-md">
                <div className="group relative w-full">
                  <div className="pointer-events-none absolute inset-0 rounded-lg bg-gradient-to-r from-sky-400/5 to-indigo-500/5 opacity-0 transition-opacity group-hover:opacity-100" aria-hidden />
                  <div className="pointer-events-none absolute inset-y-0 left-3 flex items-center">
                    <svg className="h-4 w-4 text-muted-foreground/50" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                    </svg>
                  </div>
                  <input
                    aria-label="Search"
                    placeholder="Search jobs, workers..."
                    className="relative w-full rounded-lg border border-border/50 bg-input/60 pl-9 pr-3 py-2 text-sm text-foreground placeholder:text-muted-foreground/60 outline-none transition-all focus-visible:border-accent/50 focus-visible:bg-input/80 focus-visible:ring-2 focus-visible:ring-accent/20 backdrop-blur-sm"
                  />
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Button variant="ghost" size="icon" aria-label="Toggle theme" onClick={toggleTheme} className="hover:scale-105 transition-transform">
                  {theme === 'dark' ? '🌙' : '☀️'}
                </Button>
                <div className="relative h-9 w-9 cursor-pointer transition-transform hover:scale-110" aria-label="User avatar">
                  <div className="absolute inset-0 rounded-full bg-gradient-to-br from-sky-400 via-indigo-500 to-purple-600 opacity-20 blur-sm" aria-hidden />
                  <div className="relative h-9 w-9 rounded-full bg-gradient-to-br from-sky-400 via-indigo-500 to-purple-600 flex items-center justify-center text-sm font-bold text-white shadow-lg">
                    AP
                  </div>
                </div>
              </div>
            </div>
          </header>

          <div className="w-full px-6 py-6 space-y-6">{actions}{children}</div>
        </main>
      </div>
    </div>
  );
};

export default Shell;

