// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
import { cn } from './LayoutHelpers';

export type JobStatus = 'queued' | 'processing' | 'running' | 'done' | 'completed' | 'failed' | 'online' | 'offline' | string;

type StatusBadgeProps = {
  status: JobStatus;
  className?: string;
  title?: string;
};

const statusStyles: Record<string, { bg: string; text: string; dot: string; label?: string }> = {
  queued: { bg: 'bg-muted', text: 'text-foreground', dot: 'bg-border', label: 'Queued' },
  processing: { bg: 'bg-blue-50 dark:bg-blue-900/40', text: 'text-blue-700 dark:text-blue-100', dot: 'bg-blue-500', label: 'Processing' },
  running: { bg: 'bg-blue-50 dark:bg-blue-900/40', text: 'text-blue-700 dark:text-blue-100', dot: 'bg-blue-500', label: 'Running' },
  done: { bg: 'bg-green-50 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-100', dot: 'bg-green-500', label: 'Done' },
  reviewed: { bg: 'bg-indigo-50 dark:bg-indigo-900/30', text: 'text-indigo-700 dark:text-indigo-100', dot: 'bg-indigo-500', label: 'Reviewed' },
  posted: { bg: 'bg-emerald-50 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-100', dot: 'bg-emerald-500', label: 'Posted' },
  completed: { bg: 'bg-green-50 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-100', dot: 'bg-green-500', label: 'Completed' },
  failed: { bg: 'bg-red-50 dark:bg-red-900/30', text: 'text-red-700 dark:text-red-100', dot: 'bg-red-500', label: 'Failed' },
  online: { bg: 'bg-green-50 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-100', dot: 'bg-green-500', label: 'Online' },
  offline: { bg: 'bg-slate-100 dark:bg-slate-800', text: 'text-slate-700 dark:text-slate-100', dot: 'bg-slate-400', label: 'Offline' },
  idle: { bg: 'bg-muted', text: 'text-foreground', dot: 'bg-border', label: 'Idle' },
};

const StatusBadge = ({ status, className, title }: StatusBadgeProps): JSX.Element => {
  const key = status.toLowerCase();
  const style = statusStyles[key] ?? statusStyles.queued;
  const isRunning = key === 'running' || key === 'processing';
  const label = style.label ?? status;

  return (
    <span
      title={title}
      className={cn(
        'relative inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-medium capitalize backdrop-blur-sm',
        style.bg,
        style.text,
        className,
      )}
    >
      <span className="relative flex h-2.5 w-2.5">
        {isRunning && (
          <>
            <span className={cn('absolute inline-flex h-full w-full animate-ping rounded-full opacity-75', style.dot)} />
            <span className={cn('relative inline-flex h-2.5 w-2.5 rounded-full', style.dot)} />
          </>
        )}
        {!isRunning && <span className={cn('h-2.5 w-2.5 rounded-full', style.dot)} />}
      </span>
      <span>{label}</span>
    </span>
  );
};

export default StatusBadge;

