import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
import { cn } from './LayoutHelpers';
const StatusTimeline = ({ steps }) => {
    return (_jsx("ol", { className: "relative space-y-5 border-l border-border pl-4", "aria-label": "Job progress timeline", children: steps.map((step, index) => {
            const isLast = index === steps.length - 1;
            const color = step.state === 'done'
                ? 'bg-green-500 border-green-500'
                : step.state === 'current'
                    ? 'bg-blue-500 border-blue-500 animate-pulse'
                    : 'bg-border border-border';
            return (_jsxs("li", { className: "relative", children: [_jsx("span", { className: cn('absolute -left-[0.95rem] flex h-3 w-3 items-center justify-center rounded-full border-2', color), "aria-hidden": true }), !isLast && _jsx("span", { className: "absolute -left-[0.65rem] top-3 h-full w-px bg-border", "aria-hidden": true }), _jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsx("div", { className: "text-sm font-medium text-foreground", children: step.label }), _jsx("div", { className: "text-xs text-muted-foreground", children: step.time })] })] }, step.label));
        }) }));
};
export default StatusTimeline;
