import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
import { cn } from './LayoutHelpers';
const statusStyles = {
    queued: { bg: 'bg-muted', text: 'text-foreground', dot: 'bg-border', label: 'Queued' },
    processing: { bg: 'bg-blue-50 dark:bg-blue-900/40', text: 'text-blue-700 dark:text-blue-100', dot: 'bg-blue-500', label: 'Processing' },
    running: { bg: 'bg-blue-50 dark:bg-blue-900/40', text: 'text-blue-700 dark:text-blue-100', dot: 'bg-blue-500', label: 'Running' },
    done: { bg: 'bg-green-50 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-100', dot: 'bg-green-500', label: 'Done' },
    reviewed: { bg: 'bg-indigo-50 dark:bg-indigo-900/30', text: 'text-indigo-700 dark:text-indigo-100', dot: 'bg-indigo-500', label: 'Reviewed' },
    posted: { bg: 'bg-emerald-50 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-100', dot: 'bg-emerald-500', label: 'Posted' },
    completed: { bg: 'bg-green-50 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-100', dot: 'bg-green-500', label: 'Completed' },
    failed: { bg: 'bg-red-50 dark:bg-red-900/30', text: 'text-red-700 dark:text-red-100', dot: 'bg-red-500', label: 'Failed' },
    online: { bg: 'bg-green-50 dark:bg-green-900/30', text: 'text-green-700 dark:text-green-100', dot: 'bg-green-500', label: 'Online' },
    offline: { bg: 'bg-slate-100 dark:bg-slate-800', text: 'text-slate-700 dark:text-slate-100', dot: 'bg-slate-400', label: 'Offline' },
    idle: { bg: 'bg-muted', text: 'text-foreground', dot: 'bg-border', label: 'Idle' },
};
const StatusBadge = ({ status, className, title }) => {
    const key = status.toLowerCase();
    const style = statusStyles[key] ?? statusStyles.queued;
    const isRunning = key === 'running' || key === 'processing';
    const label = style.label ?? status;
    return (_jsxs("span", { title: title, className: cn('relative inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-medium capitalize backdrop-blur-sm', style.bg, style.text, className), children: [_jsxs("span", { className: "relative flex h-2.5 w-2.5", children: [isRunning && (_jsxs(_Fragment, { children: [_jsx("span", { className: cn('absolute inline-flex h-full w-full animate-ping rounded-full opacity-75', style.dot) }), _jsx("span", { className: cn('relative inline-flex h-2.5 w-2.5 rounded-full', style.dot) })] })), !isRunning && _jsx("span", { className: cn('h-2.5 w-2.5 rounded-full', style.dot) })] }), _jsx("span", { children: label })] }));
};
export default StatusBadge;
