// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
import { cn } from './LayoutHelpers';

export type TimelineStep = {
  label: string;
  time: string;
  state: 'pending' | 'current' | 'done';
};

type StatusTimelineProps = {
  steps: TimelineStep[];
};

const StatusTimeline = ({ steps }: StatusTimelineProps): JSX.Element => {
  return (
    <ol className="relative space-y-5 border-l border-border pl-4" aria-label="Job progress timeline">
      {steps.map((step, index) => {
        const isLast = index === steps.length - 1;
        const color =
          step.state === 'done'
            ? 'bg-green-500 border-green-500'
            : step.state === 'current'
            ? 'bg-blue-500 border-blue-500 animate-pulse'
            : 'bg-border border-border';
        return (
          <li key={step.label} className="relative">
            <span className={cn('absolute -left-[0.95rem] flex h-3 w-3 items-center justify-center rounded-full border-2', color)} aria-hidden />
            {!isLast && <span className="absolute -left-[0.65rem] top-3 h-full w-px bg-border" aria-hidden />}
            <div className="flex items-center justify-between gap-3">
              <div className="text-sm font-medium text-foreground">{step.label}</div>
              <div className="text-xs text-muted-foreground">{step.time}</div>
            </div>
          </li>
        );
      })}
    </ol>
  );
};

export default StatusTimeline;

