import { jsx as _jsx } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
import { createContext, useContext, useEffect, useMemo, useState } from 'react';
const ThemeContext = createContext(undefined);
const THEME_KEY = 'devpilot-theme';
export const ThemeProvider = ({ children }) => {
    const [theme, setTheme] = useState(() => {
        if (typeof window === 'undefined')
            return 'light';
        const saved = window.localStorage.getItem(THEME_KEY);
        if (saved === 'light' || saved === 'dark')
            return saved;
        if (typeof window.matchMedia === 'function') {
            return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        }
        return 'light';
    });
    useEffect(() => {
        const root = document.documentElement;
        if (theme === 'dark') {
            root.classList.add('theme-dark');
        }
        else {
            root.classList.remove('theme-dark');
        }
        window.localStorage.setItem(THEME_KEY, theme);
    }, [theme]);
    const value = useMemo(() => ({
        theme,
        toggleTheme: () => setTheme((prev) => (prev === 'light' ? 'dark' : 'light')),
    }), [theme]);
    return _jsx(ThemeContext.Provider, { value: value, children: children });
};
export const useTheme = () => {
    const ctx = useContext(ThemeContext);
    if (!ctx) {
        throw new Error('useTheme must be used within ThemeProvider');
    }
    return ctx;
};
export default ThemeProvider;
