// AUTOGENERATED BY COPILOT PROMPT - archived mock page
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import StatusBadge from '../../components/StatusBadge';
import Button from '../../components/ui/Button';
import Card from '../../components/ui/Card';
import SkeletonRow from '../../components/ui/SkeletonRow';
import IconChevronRight from '../../components/ui/IconChevronRight';
import { useMockJobs } from '../../hooks/__deprecated__/useMockJobs';

const JobsPage = (): JSX.Element => {
  const navigate = useNavigate();
  const { data: jobs, isLoading } = useMockJobs();
  const [filter, setFilter] = useState<'all' | 'queued' | 'running' | 'completed' | 'failed'>('all');

  const filteredJobs = useMemo(() => {
    if (!jobs) return [];
    if (filter === 'all') return jobs;
    return jobs.filter((job) => job.status === filter);
  }, [jobs, filter]);

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Job Queue</h2>
          <p className="text-sm text-muted-foreground">Monitor recent reviews and processing states.</p>
        </div>
        <div className="flex items-center gap-2">
          <select
            aria-label="Filter jobs by status"
            value={filter}
            onChange={(e) => setFilter(e.target.value as typeof filter)}
            className="rounded-md border border-border bg-input px-3 py-2 text-sm text-foreground outline-none focus-visible:ring-2 focus-visible:ring-accent"
          >
            <option value="all">All statuses</option>
            <option value="queued">Queued</option>
            <option value="running">Running</option>
            <option value="completed">Completed</option>
            <option value="failed">Failed</option>
          </select>
          <Button variant="primary" onClick={() => window.alert('New review flow is mocked')}>
            New Review
          </Button>
        </div>
      </div>

      <Card>
        <div className="overflow-hidden">
          <table className="w-full table-fixed">
            <thead className="bg-muted/50 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              <tr className="grid grid-cols-[1fr,1.3fr,0.9fr,0.8fr,0.3fr] items-center gap-2 px-3 py-2">
                <th scope="col" className="text-left">Repository</th>
                <th scope="col" className="text-left">Pull Request</th>
                <th scope="col" className="text-left">Status</th>
                <th scope="col" className="text-left">Last Updated</th>
                <th scope="col" className="text-right">Actions</th>
              </tr>
            </thead>

            <tbody className="divide-y divide-border">
              {isLoading && (
                <tr>
                  <td colSpan={5} className="px-2 py-3">
                    <div className="space-y-2">
                      {Array.from({ length: 5 }).map((_, idx) => (
                        <SkeletonRow key={idx} />
                      ))}
                    </div>
                  </td>
                </tr>
              )}

              {!isLoading && filteredJobs.length === 0 && (
                <tr>
                  <td colSpan={5} className="px-6 py-12">
                    <div className="flex flex-col items-center justify-center gap-2 text-center">
                      <p className="text-sm font-medium text-foreground">No jobs for this filter.</p>
                      <p className="text-sm text-muted-foreground">Create a new review or adjust the filter.</p>
                      <Button variant="secondary" onClick={() => setFilter('all')}>
                        Reset filter
                      </Button>
                    </div>
                  </td>
                </tr>
              )}

              {!isLoading &&
                filteredJobs.map((job) => (
                  <tr
                    key={job.id}
                    tabIndex={0}
                    onClick={() => navigate(`/jobs/${job.id}`)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault();
                        navigate(`/jobs/${job.id}`);
                      }
                    }}
                    className="group grid grid-cols-[1fr,1.3fr,0.9fr,0.8fr,0.3fr] items-center gap-2 px-3 py-3 text-left transition hover:bg-muted focus-visible:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-panel cursor-pointer"
                  >
                    <td className="flex items-center gap-2 text-sm font-medium text-foreground">
                      <span className="inline-flex h-8 w-8 items-center justify-center rounded-md bg-muted text-xs font-semibold">RP</span>
                      <span className="truncate">{job.repository}</span>
                    </td>
                    <td className="truncate text-sm text-foreground">
                      <div className="line-clamp-2">{job.prTitle}</div>
                      <div className="text-xs text-muted-foreground">PR #{job.prNumber} | {job.author}</div>
                    </td>
                    <td>
                      <StatusBadge status={job.status} />
                    </td>
                    <td className="text-sm text-muted-foreground">{job.updatedAt}</td>
                    <td className="flex items-center justify-end">
                      <IconChevronRight className="h-4 w-4 text-border transition group-hover:translate-x-0.5 group-hover:text-foreground" />
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};

export default JobsPage;
