// AUTOGENERATED BY COPILOT PROMPT - archived mock page
import StatusBadge from '../../components/StatusBadge';
import Button from '../../components/ui/Button';
import Card from '../../components/ui/Card';

type Worker = {
  id: string;
  name: string;
  status: 'running' | 'idle' | 'failed';
  currentJob?: string;
  heartbeat: string;
};

const mockWorkers: Worker[] = [
  { id: 'w1', name: 'worker-edge-1', status: 'running', currentJob: 'job #3481', heartbeat: 'Just now' },
  { id: 'w2', name: 'worker-edge-2', status: 'running', currentJob: 'job #3470', heartbeat: '30s ago' },
  { id: 'w3', name: 'worker-intake', status: 'idle', heartbeat: '2m ago' },
  { id: 'w4', name: 'worker-legacy', status: 'failed', heartbeat: '12m ago' },
];

const WorkersPage = (): JSX.Element => {
  const running = mockWorkers.filter((w) => w.status === 'running').length;
  const idle = mockWorkers.filter((w) => w.status === 'idle').length;
  const failed = mockWorkers.filter((w) => w.status === 'failed').length;

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Workers</h2>
          <p className="text-sm text-muted-foreground">Operational view of running agents (mocked).</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" onClick={() => window.alert('Refresh is mocked')}>
            Refresh
          </Button>
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <Card title="Total" subtitle="All workers">
          <p className="text-2xl font-semibold text-foreground">{mockWorkers.length}</p>
        </Card>
        <Card title="Running" subtitle="Processing">
          <p className="text-2xl font-semibold text-foreground">{running}</p>
        </Card>
        <Card title="Idle" subtitle="Standing by">
          <p className="text-2xl font-semibold text-foreground">{idle}</p>
        </Card>
        <Card title="Failed" subtitle="Needs attention">
          <p className="text-2xl font-semibold text-foreground">{failed}</p>
        </Card>
      </div>

      <Card title="Fleet" subtitle="Health, assignment, and heartbeats">
        <div className="overflow-hidden">
          <table className="w-full table-fixed divide-y divide-border">
            <thead className="bg-muted/50 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              <tr className="grid grid-cols-[1.2fr,1fr,1fr,0.6fr] items-center gap-2 px-3 py-2">
                <th scope="col" className="text-left">Name</th>
                <th scope="col" className="text-left">Status</th>
                <th scope="col" className="text-left">Current Job</th>
                <th scope="col" className="text-right">Actions</th>
              </tr>
            </thead>
            <tbody>
              {mockWorkers.map((worker) => (
                <tr
                  key={worker.id}
                  className="grid grid-cols-[1.2fr,1fr,1fr,0.6fr] items-center gap-2 px-3 py-3 text-sm"
                >
                  <td className="space-y-1">
                    <p className="font-semibold text-foreground">{worker.name}</p>
                    <p className="text-xs text-muted-foreground">Heartbeat: {worker.heartbeat}</p>
                  </td>
                  <td>
                    <StatusBadge status={worker.status} />
                  </td>
                  <td className="text-sm text-muted-foreground">{worker.currentJob ?? '--'}</td>
                  <td className="flex justify-end">
                    <Button variant="outline" size="sm" disabled>
                      Restart
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};

export default WorkersPage;
