// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
import { useEffect, useMemo, useState } from 'react';
import { JobStatus } from '../components/StatusBadge';
import type { TimelineStep } from '../components/StatusTimeline';

export type Job = {
  id: string;
  repository: string;
  prTitle: string;
  prNumber: number;
  branch: string;
  author: string;
  status: JobStatus;
  updatedAt: string;
  review: string;
  steps: TimelineStep[];
  logs: string;
};

const reviewMarkdown = `## Summary
- Automated review completed with inline lint hints.
- Coverage stable; no regressions detected.

## Issues
- Missing null check in job detail loader when id is undefined.
- Worker heartbeat threshold could be configurable via env.

## Suggestions
- Consider adding structured logging (JSON) for queue events.
- Add optimistic UI updates when jobs transition to running.

\`\`\`bash
git fetch origin feature/new-ci && git checkout feature/new-ci
pnpm lint && pnpm test
\`\`\`
`;

const baseSteps: TimelineStep[] = [
  { label: 'Queued', time: '09:00', state: 'done' },
  { label: 'Fetching', time: '09:03', state: 'done' },
  { label: 'Analyzing', time: '09:05', state: 'current' },
  { label: 'Writing', time: '--', state: 'pending' },
  { label: 'Done', time: '--', state: 'pending' },
];

const mockJobs: Job[] = [
  {
    id: '3481',
    repository: 'devpilot/frontend',
    prTitle: 'Improve job detail markdown rendering',
    prNumber: 128,
    branch: 'feature/markdown-enhancements',
    author: 'Alex Park',
    status: 'running',
    updatedAt: '2m ago',
    review: reviewMarkdown,
    steps: baseSteps,
    logs: '[09:03:00] Checkout complete\n[09:03:04] pnpm install\n[09:04:12] pnpm lint\n[09:05:10] Running review...\n[09:06:18] Streaming tokens...\n',
  },
  {
    id: '3479',
    repository: 'devpilot/backend',
    prTitle: 'Add retry logic for queue workers',
    prNumber: 312,
    branch: 'chore/retry-backoff',
    author: 'Samir Khan',
    status: 'completed',
    updatedAt: '28m ago',
    review: reviewMarkdown,
    steps: [
      { label: 'Queued', time: '07:42', state: 'done' },
      { label: 'Fetching', time: '07:44', state: 'done' },
      { label: 'Analyzing', time: '07:48', state: 'done' },
      { label: 'Writing', time: '07:51', state: 'done' },
      { label: 'Done', time: '07:53', state: 'done' },
    ],
    logs: '[07:42:00] Job created\n[07:44:20] Fetching repo\n[07:48:10] Completed analysis\n[07:53:00] Review stored\n',
  },
  {
    id: '3478',
    repository: 'devpilot/worker',
    prTitle: 'Reduce noise in worker metrics',
    prNumber: 88,
    branch: 'fix/metrics-noise',
    author: 'Priya Desai',
    status: 'queued',
    updatedAt: '39m ago',
    review: reviewMarkdown,
    steps: [
      { label: 'Queued', time: '08:22', state: 'current' },
      { label: 'Fetching', time: '--', state: 'pending' },
      { label: 'Analyzing', time: '--', state: 'pending' },
      { label: 'Writing', time: '--', state: 'pending' },
      { label: 'Done', time: '--', state: 'pending' },
    ],
    logs: '[08:22:10] Awaiting worker assignment\n',
  },
  {
    id: '3474',
    repository: 'devpilot/frontend',
    prTitle: 'Refine keyboard focus states',
    prNumber: 101,
    branch: 'ux/focus-styles',
    author: 'Lina Cho',
    status: 'failed',
    updatedAt: '1h ago',
    review: reviewMarkdown,
    steps: [
      { label: 'Queued', time: '06:18', state: 'done' },
      { label: 'Fetching', time: '06:20', state: 'done' },
      { label: 'Analyzing', time: '06:23', state: 'done' },
      { label: 'Writing', time: '06:28', state: 'done' },
      { label: 'Done', time: '06:29', state: 'done' },
    ],
    logs: '[06:28:11] Error: ESLint rule not found\n[06:28:15] Job failed\n',
  },
  {
    id: '3470',
    repository: 'devpilot/api-gateway',
    prTitle: 'Add request tracing headers',
    prNumber: 72,
    branch: 'feature/trace-ids',
    author: 'Morgan Hill',
    status: 'running',
    updatedAt: '5m ago',
    review: reviewMarkdown,
    steps: [
      { label: 'Queued', time: '08:52', state: 'done' },
      { label: 'Fetching', time: '08:54', state: 'done' },
      { label: 'Analyzing', time: '08:59', state: 'current' },
      { label: 'Writing', time: '--', state: 'pending' },
      { label: 'Done', time: '--', state: 'pending' },
    ],
    logs: '[08:54:10] Fetch complete\n[08:59:00] Analyzing code paths\n',
  },
];

export const useMockJobs = () => {
  const [data, setData] = useState<Job[] | undefined>();
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setData(mockJobs);
      // TODO: replace mock with useQuery('/api/jobs') or socket subscription
      setIsLoading(false);
    }, 200 + Math.random() * 200);
    return () => window.clearTimeout(timer);
  }, []);

  return { data, isLoading, error: undefined as undefined };
};

export const useMockJob = (id?: string) => {
  const [job, setJob] = useState<Job | undefined>();
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    const timer = window.setTimeout(() => {
      setJob(mockJobs.find((j) => j.id === id));
      // TODO: replace mock with useQuery(['/api/jobs', id]) or socket subscription
      setIsLoading(false);
    }, 200 + Math.random() * 200);
    return () => window.clearTimeout(timer);
  }, [id]);

  const related = useMemo(() => mockJobs.slice(0, 3), []);

  return { job, related, isLoading, error: undefined as undefined };
};

