import { jsx as _jsx } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
const IconChevronRight = ({ className }) => (_jsx("svg", { className: className, xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 24 24", strokeWidth: 1.5, stroke: "currentColor", "aria-hidden": true, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M9 5l7 7-7 7" }) }));
export default IconChevronRight;
