// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments

const IconChevronRight = ({ className }: { className?: string }): JSX.Element => (
  <svg
    className={className}
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    strokeWidth={1.5}
    stroke="currentColor"
    aria-hidden
  >
    <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
  </svg>
);

export default IconChevronRight;

