import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import { cn } from '../LayoutHelpers';
const Sidebar = ({ logo, appName = 'DevPilot', navItems, footer, className }) => {
    const groupedItems = navItems.reduce((acc, item) => {
        const group = item.section ?? 'General';
        if (!acc[group])
            acc[group] = [];
        acc[group].push(item);
        return acc;
    }, {});
    return (_jsxs("aside", { className: cn('hidden md:flex h-screen w-60 flex-col md:sticky md:top-0 z-20', 'glass-strong relative', 'shadow-2xl shadow-primary-500/5', 'before:absolute before:inset-0 before:bg-gradient-to-b before:from-primary-500/5 before:via-transparent before:to-purple-500/5 before:pointer-events-none', className), role: "navigation", "aria-label": "Primary navigation", children: [_jsx("div", { className: "absolute right-0 top-6 bottom-6 w-px divider-vertical", "aria-hidden": "true" }), _jsxs("div", { className: "relative flex items-center gap-3 px-5 py-5 overflow-hidden animate-fadeInDown", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-primary-500/10 via-primary-600/10 to-primary-700/10 animate-gradient-shift", "aria-hidden": "true" }), _jsx("div", { className: "absolute -top-10 -left-10 w-32 h-32 rounded-full bg-primary-400/20 blur-3xl animate-float", "aria-hidden": "true" }), _jsx("div", { className: "absolute -bottom-10 -right-10 w-32 h-32 rounded-full bg-purple-400/20 blur-3xl animate-float delay-1000", "aria-hidden": "true" }), _jsxs("div", { className: "relative h-10 w-10 rounded-xl bg-gradient-to-br from-primary-400 via-primary-500 to-primary-600 text-white flex items-center justify-center font-bold text-sm shadow-lg shadow-primary-500/30 hover:scale-110 transition-transform duration-300", children: [_jsx("span", { className: "absolute -inset-1 rounded-2xl border border-primary/40 animate-spin [animation-duration:8s]", "aria-hidden": "true" }), _jsx("span", { className: "relative", children: logo || 'DP' })] }), _jsxs("div", { className: "relative flex items-center gap-2 min-w-0", children: [_jsx("div", { className: "font-bold tracking-tight text-lg text-gradient truncate", children: appName }), _jsxs("span", { className: "inline-flex items-center gap-1 rounded-full glass px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-primary", children: [_jsx("span", { className: "h-1.5 w-1.5 rounded-full bg-success animate-pulse", "aria-hidden": "true" }), "Live"] })] }), _jsx("div", { className: "absolute left-5 right-5 bottom-0 h-px divider-horizontal", "aria-hidden": "true" })] }), _jsx("nav", { className: "flex-1 px-3 py-5 space-y-1.5 overflow-y-auto scrollbar-thin", children: Object.entries(groupedItems).map(([group, items]) => (_jsxs("div", { className: "space-y-1.5", children: [_jsx("p", { className: "px-3 pb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-text-tertiary", children: group }), items.map((item, idx) => {
                            if (item.disabled || item.soon) {
                                return (_jsxs("div", { className: cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium', 'text-text-tertiary/50 cursor-not-allowed'), "aria-label": item.soon ? `${item.label} coming soon` : item.label, children: [item.icon && _jsx("span", { className: "inline-flex items-center opacity-50", children: item.icon }), _jsx("span", { children: item.label }), item.soon && (_jsx("span", { className: "ml-auto rounded-full glass px-2 py-0.5 text-[10px] uppercase tracking-wide animate-pulse", children: "Soon" })), item.badge && _jsx("span", { className: "ml-auto badge badge-primary", children: item.badge })] }, `${item.label}-${idx}`));
                            }
                            if (!item.to)
                                return null;
                            return (_jsx(NavLink, { to: item.to, className: ({ isActive }) => cn('group relative flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium', 'outline-none transition-all duration-300', 'focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-primary focus-visible:ring-offset-bg-elevated', isActive
                                    ? 'glass bg-gradient-to-r from-primary/15 to-primary/5 text-primary shadow-md shadow-primary-500/10 scale-[1.02]'
                                    : 'text-text-secondary hover:glass hover:bg-gradient-to-r hover:from-bg-surface/50 hover:to-transparent hover:text-text-primary hover:scale-[1.02] hover:shadow-sm'), children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && (_jsx("span", { className: "absolute left-0 h-4 w-1 rounded-r bg-gradient-to-b from-primary-400 to-primary-600 shadow-lg shadow-primary-500/50", "aria-hidden": "true" })), item.icon && (_jsx("span", { className: cn('inline-flex items-center transition-all duration-300', isActive ? 'text-primary drop-shadow-glow' : 'opacity-60 group-hover:opacity-100 group-hover:scale-110'), children: item.icon })), _jsx("span", { className: "relative", children: item.label }), item.badge && (_jsx("span", { className: cn('ml-auto rounded-full px-2 py-0.5 text-xs font-semibold transition-all duration-300', isActive
                                                ? 'glass-strong text-primary shadow-sm'
                                                : 'glass text-text-secondary group-hover:glass-strong group-hover:text-primary'), children: item.badge }))] })) }, `${item.label}-${idx}`));
                        })] }, group))) }), footer && (_jsxs("div", { className: "glass-card px-4 py-3 animate-fadeInUp", children: [_jsx("div", { className: "mb-3 divider-horizontal", "aria-hidden": "true" }), footer] }))] }));
};
export default Sidebar;
