import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import { cn } from '../LayoutHelpers';
const Sidebar = ({ logo, appName = 'DevPilot', navItems, footer, className }) => {
    return (_jsxs("aside", { className: cn('hidden md:flex h-screen w-60 flex-col', 'border-r border-border/50 bg-elevated/50 backdrop-blur-xl', 'sticky top-0', className), role: "navigation", "aria-label": "Primary navigation", children: [_jsxs("div", { className: "relative flex items-center gap-3 px-5 py-5 border-b border-border/50 overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-primary-500/10 via-primary-600/10 to-primary-700/10", "aria-hidden": "true" }), _jsx("div", { className: "relative h-10 w-10 rounded-xl bg-gradient-to-br from-primary-400 via-primary-500 to-primary-600 text-white flex items-center justify-center font-bold text-sm shadow-lg shadow-primary-500/20", children: logo || 'DP' }), _jsx("div", { className: "relative font-bold tracking-tight text-lg bg-gradient-to-r from-text-primary to-text-secondary bg-clip-text", children: appName })] }), _jsx("nav", { className: "flex-1 px-3 py-5 space-y-1.5 overflow-y-auto scrollbar-thin", children: navItems.map((item, idx) => {
                    if (item.disabled || item.soon) {
                        return (_jsxs("div", { className: cn('flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium', 'text-text-tertiary/50 cursor-not-allowed'), "aria-label": item.soon ? `${item.label} coming soon` : item.label, children: [item.icon && _jsx("span", { className: "inline-flex items-center opacity-50", children: item.icon }), _jsx("span", { children: item.label }), item.soon && (_jsx("span", { className: "ml-auto rounded-full bg-muted/50 px-2 py-0.5 text-[10px] uppercase tracking-wide", children: "Soon" })), item.badge && _jsx("span", { className: "ml-auto badge badge-primary", children: item.badge })] }, `${item.label}-${idx}`));
                    }
                    if (!item.to)
                        return null;
                    return (_jsx(NavLink, { to: item.to, className: ({ isActive }) => cn('group relative flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium', 'outline-none transition-all duration-200', 'focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-primary focus-visible:ring-offset-bg-elevated', isActive
                            ? 'bg-gradient-to-r from-primary/10 to-primary/5 text-primary shadow-sm'
                            : 'text-text-secondary hover:bg-gradient-to-r hover:from-bg-surface hover:to-transparent hover:text-text-primary hover:scale-[1.02]'), children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("span", { className: "absolute left-0 h-4 w-1 rounded-r bg-primary", "aria-hidden": "true" }), item.icon && (_jsx("span", { className: cn('inline-flex items-center transition-all', isActive ? 'text-primary' : 'opacity-50 group-hover:opacity-100'), children: item.icon })), _jsx("span", { children: item.label }), item.badge && (_jsx("span", { className: "ml-auto rounded-full bg-primary-100 dark:bg-primary-900/30 px-2 py-0.5 text-xs font-semibold text-primary-700 dark:text-primary-300", children: item.badge }))] })) }, `${item.label}-${idx}`));
                }) }), footer && (_jsx("div", { className: "border-t border-border/50 bg-gradient-to-b from-transparent to-bg-surface/20 px-4 py-3", children: footer }))] }));
};
export default Sidebar;
