import { jsx as _jsx } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
import { cn } from '../LayoutHelpers';
const SkeletonRow = ({ className }) => (_jsx("div", { className: cn('h-12 w-full animate-pulse rounded-md bg-muted', className), "aria-hidden": true }));
export default SkeletonRow;
