// AUTOGENERATED BY COPILOT PROMPT â€“ replace mocks with real API calls at TODO comments
import { cn } from '../LayoutHelpers';

type SkeletonRowProps = {
  className?: string;
};

const SkeletonRow = ({ className }: SkeletonRowProps): JSX.Element => (
  <div className={cn('h-12 w-full animate-pulse rounded-md bg-muted', className)} aria-hidden />
);

export default SkeletonRow;

