import { jsx as _jsx } from "react/jsx-runtime";
// AUTOGENERATED BY COPILOT PROMPT - replace mocks with real API calls at TODO comments
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import App from './App';
import { ThemeProvider } from './components/ThemeProvider';
import './styles/globals.css';
import { initRealtime } from './lib/socket';
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            refetchOnWindowFocus: false,
            retry: 1,
        },
    },
});
initRealtime(queryClient);
const container = document.getElementById('root');
if (!container) {
    throw new Error('Root container missing');
}
ReactDOM.createRoot(container).render(_jsx(React.StrictMode, { children: _jsx(QueryClientProvider, { client: queryClient, children: _jsx(ThemeProvider, { children: _jsx(BrowserRouter, { children: _jsx(App, {}) }) }) }) }));
